const exceptions = {
    userAlreadyExists: "userAlreadyExists",
    invalidUserId: "invalidUserId",
    missingTokenId: "missingTokenId",
    userDoesNotExist: "userDoesNotExist",
    cannotFollowSelf: "cannotFollowSelf",
    emailIsNotVerified: "emailIsNotVerified",
    userIsNotAdmin: "userIsNotAdmin",
    invalidToken: "invalidToken",
    missingEmail: "missingEmail",
    missingPassword: "missingPassword",
    missingPasswordResetObject: "missingPasswordResetObject",
    missingEmailVerificationObject: "missingEmailVerificationObject",
    couldNotCreateToken: "couldNotCreateToken",
    couldNotCreatePasswordHash: "couldNotCreatePasswordHash",
    missingUserUpdate: "missingUserUpdate",
    invalidFollowType: "invalidFollowType",
    invalidImageType: "invalidImageType",
    invalidPost: "invalidPost",
    couldNotCreateProfilePhotoUrl: "couldNotCreateProfilePhotoUrl",
    couldNotCreateUser: "couldNotCreateUser",
    couldNotSaveToken: "couldNotSaveToken",
    unknown: "unknown"
}

export default exceptions